### ISSUE TITLE
check_data.py gave error on given solution.json file

### ISSUE THREAD

**Issue by type-null** [GOCompetition/C3DataUtilities#6]
```python
python C3DataUtilities\check_data.py -p "{path prefix}\C3S0_20221208\D1\C3S0N00003\scenario_003.json" -s "{path prefix}\C3S0_20221208\D1\C3S0N00003\scenario_003_solution.json"
```

This command testing problem dataset and corresponding solution file gave the warning/error below:
```python
C:\Users\me\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:318: SparseEfficiencyWarning: splu requires CSC matrix format
  warn('splu requires CSC matrix format', SparseEfficiencyWarning)
Traceback (most recent call last):
  File "C3DataUtilities\check_data.py", line 85, in <module>
    validation.check_data(problem, args.solution, default_config, args.configuration, args.parameters, args.summary_csv, args.summary_json, args.data_errors, args.ignored_errors, args.solution_errors)
  File "C3DataUtilities\datautilities\validation.py", line 865, in check_data
    solution_evaluator.run()
  File "C3DataUtilities\datautilities\utils.py", line 15, in timed
    result = function(*args, **kw)
  File "C3DataUtilities\datautilities\evaluation.py", line 187, in run
    self.eval_post_contingency_model()
  File "C3DataUtilities\datautilities\utils.py", line 15, in timed
    result = function(*args, **kw)
  File "C3DataUtilities\datautilities\evaluation.py", line 1234, in eval_post_contingency_model
    ctgmodel.eval_post_contingency_model(self)
  File "C3DataUtilities\datautilities\utils.py", line 15, in timed
    result = function(*args, **kw)
  File "C3DataUtilities\datautilities\ctgmodel.py", line 228, in eval_post_contingency_model
    m_br_t = nonref_bus_br_inc[:, br_delta_t].toarray()
TypeError: 'coo_matrix' object is not subscriptable
```

**Comment by jesseholzerpnnl** [comment]
Hi @type-null, thank you for reporting this. Other users have encountered a similar issue. We have not determined the best solution yet, but it seems that ensuring python>=3.8 and scipy>=1.9 fixes this.
